# Dir
data_dir : '/data/ephemeral/data/'
total_data_name : 'total.csv'    # Train + Test (answerCode -1 제외 (2525956행))
test_data_name : 'test_data.csv' # Origin Test Data (260114행)

sweep_yaml : '/data/ephemeral/base_code/code/SAINT+/sweep.yaml'

model_dir : '/data/ephemeral/model/'
model_name : 'SAINT+_bestparam.pt'

submit_dir : '/data/ephemeral/submit/'
submit_name : 'SAINT+_bestparam.csv'

# Model
n_layers : 2      # Multihead Attention Layer의 수 (Default : 2)
n_heads : 4       # One Multihead Attention Layer의 Head 수 (Default : 4)
d_model : 64      # Embedding Dimension Size 수 (Default : 64)
max_len : 1000    # Positional Encoding의 Max Length (Default : 1000)
seq_len : 100     # Sequence Length (Default : 100)
n_question : 9454 # assessmentItemID 수 (Default : 9454)
n_test : 1537     # testID 수 (Default : 1537)

# Train
seed : 42
device : 'cuda'
num_workers : 8
scale : False

dropout : 0.1        # Default : 0.2
n_epochs : 100
patience : 10
batch_size : 32      # Default : 64
lr : 0.001           # Default : 0.001
optimizer : 'Adam'  # 'Adam', 'AdamW', 'NAdam'
scheduler : 'plateau'
warmup_step : 4000

# wandb
# https://wandb.ai/authorize
key : 
project : 'SAINT+'
runname : 'SAINT+_bestparam'